version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: borrow_mysqldb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: borrow_mysqldb
    ports:
    - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mysql_database_network

  redis:
    image: redis:latest
    container_name: borrow_myredis
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - mysql_database_network
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: mysql_data_myadmin_borrow_mysqldb
    restart: always
    ports:
      - "8081:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=borrow_mysqldb
      - MYSQL_ROOT_PASSWORD=secret
    depends_on:
      - mysql
    networks:
      - mysql_database_network 
networks:
  mysql_database_network: 
    driver: bridge
volumes:
  mysql_data:
    name: mysql_data
  redis_data:
